### ISSUE TITLE
Error when try run Guillotine algorithm

### ISSUE THREAD

**Issue by cracktichi** [ssbothwell/greedypacker#2]
How can run **demo/matplotlib_demo.py** with pack_algo = 'guillotine'?
I try run with guillotine with any heuristic of  guillotine  but i facing an error when i run with
**$ python matplotlib_demo.py**:
![capture](https://user-images.githubusercontent.com/38685783/40770411-c33eba1a-64e4-11e8-84ac-f1201e1849a5.JPG)

Bellow my custom code in **matplotlib_demo.py**:

![capture](https://user-images.githubusercontent.com/38685783/40770471-f5b355aa-64e4-11e8-832d-4b6772ed0518.JPG)

**Comment by ssbothwell** [comment]
You aren't instantiating `BinManager` correctly. Try this:
    ```M = g.BinManager(10, 6, pack_algo='guillotine', heuristic='best_shortside', rotation=False, sorting=False)```

**Comment by cracktichi** [comment]
Hi bothwell,
I had modifier as you talk but issue still occurs
![image](https://user-images.githubusercontent.com/38685783/41208951-1320515e-6d52-11e8-893c-f4d73fb852de.png)

Error:
![image](https://user-images.githubusercontent.com/38685783/41208986-521f1fc0-6d52-11e8-8e75-68d1fc54cb91.png)
